### ISSUE TITLE
Copy Carthage Frameworks error

### ISSUE THREAD

**Issue by SebastianThiebaud** [MonsantoCo/FirebaseFramework#1]
Hello,

First and foremost, thank you for this repository, it's incredibly useful. I've been trying to configure my project to include Firestore frameworks and I'm running into this error:

```
Failed to read file or folder at /Users/foo/Repositories/bar/Carthage/Build/iOS/Firebase/Analytics/FirebaseAnalytics.framework
Command /bin/sh failed with exit code 1
```

Do you have any idea what's going wrong here?

Thank you

**Comment by schlingding** [comment]
Looks like a potential Carthage setup issue. https://github.com/Carthage/Carthage#getting-started

If all else fails, run carthage update once again and/or delete the problematic carthage cache `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and see if it clears up the issue.

**Comment by SebastianThiebaud** [comment]
No luck... You can confirm that `master` is working for you, right?

It's interesting that Fabric and Crashlytics work without any issue but the following frameworks are causing this issue:
```
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Analytics/FirebaseAnalytics.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Analytics/FirebaseCore.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Analytics/FirebaseCoreDiagnostics.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Analytics/FirebaseInstanceID.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Analytics/FirebaseNanoPB.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Analytics/nanopb.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Firestore/BoringSSL.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Firestore/gRPC-Core.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Firestore/FirebaseFirestore.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Firestore/gRPC-ProtoRPC.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Firestore/gRPC-RxLibrary.framework",
"$(SRCROOT)/Carthage/Build/iOS/Firebase/Firestore/gRPC.framework",
```

**Comment by schlingding** [comment]
I just updated the framework and tagged as 4.10.0 as well as updated the README.md. Note that if carthage has updated correctly, some frameworks have moved folders to be more logical.

I created a brand new project, followed the directions in the readme and it seemed to work as intended.

**Comment by schlingding** [comment]
Assuming the issue was resolved.
